name: Checks
on: [push, pull_request]
jobs:
  check:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
        with:
          version: '0.8.22'
      - run: uv sync --frozen --python 3.13
      - run: uv run python scripts/check.py
      - run: uv run python scripts/build.py --without-runtime
        if: runner.os != 'Linux'
